# Generated by Django 5.2.1 on 2025-05-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('clothing', 'Одежда'), ('books', 'Книги'), ('furniture', 'Мебель'), ('other', 'Другое')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('new', 'Новое'), ('used', 'Б/у'), ('broken', 'Требует ремонта')], max_length=10),
        ),
    ]
